/*
 * midi_common.h
 *
 *  Created on: Aug 2, 2025
 *      Author: ada
 */

#ifndef INC_MIDI_DEFS_H_
#define INC_MIDI_DEFS_H_

#define MIDI_STATUS_NOTE_OFF        0x80
#define MIDI_STATUS_NOTE_ON         0x90
#define MIDI_STATUS_POLY_AFTERTOUCH 0xA0
#define MIDI_STATUS_CONTROL_CHANGE  0xB0
#define MIDI_STATUS_PROGRAM_CHANGE  0xC0
#define MIDI_STATUS_CH_AFTERTOUCH   0xD0
#define MIDI_STATUS_PITCH_WHEEL     0xE0

#define MIDI_STATUS_SYSEX_START		0xF0
#define MIDI_STATUS_SYSEX_END		0xF7

#define MIDI_STATUS_QFRAME_MTC		0xF1
#define MIDI_STATUS_SONG_PTR		0xF2
#define MIDI_STATUS_SONG_SELECT		0xF3
#define MIDI_STATUS_TUNE_REQUEST	0xF6

#define MIDI_STATUS_TIMING_CLOCK    0xF8
#define MIDI_STATUS_START           0xFA
#define MIDI_STATUS_CONTINUE        0xFB
#define MIDI_STATUS_STOP            0xFC
#define MIDI_STATUS_ACTIVE_SENSING  0xFE
#define MIDI_STATUS_SYSTEM_RESET    0xFF

#define MIDI_SYSEX_MTC				0x7F

#define MIDI_CC_VOLUME				0x07
#define MIDI_CC_MODWHEEL			0x01
#define MIDI_CC_BANK_MSB			0x00
#define MIDI_CC_BANK_LSB			0x20

#define MIDI_ROLAND_MANUF_ID		0x41
#define MIDI_ROLAND_CC_FILTER_KNOB	0x80
#define MIDI_ROLAND_CC_MOD_KNOB		0x81
#define MIDI_ROLAND_CC_FX_KNOB		0x82
#define MIDI_ROLAND_CC_SOUND_KNOB	0x83

#endif /* INC_MIDI_DEFS_H_ */
